View products front end
AndrewRobins51413/wicked-sales-js pull request #2
Opened 2020-01-14 23:42 UTC by AndrewRobins51413

2020-01-15 01:25 UTC, thebearingedge requested changes
Please let me know when this is up-to-date

2020-01-16 00:01 UTC, thebearingedge requested changes

2020-01-16 00:01 UTC, thebearingedge commented on package.json
> +    "react-bootstrap": "1.0.0-beta.16",
You can delete `react-bootstrap` and `bootstrap` from your `package.json`.

2020-01-16 00:01 UTC, thebearingedge commented on client/components/product-list.jsx
> +                </div> */}
Please delete commented out code.

2020-01-16 00:01 UTC, thebearingedge commented on client/components/product-list.jsx
> +// import ReactDOM from "react-dom"
You can delete this import if you don't need it.

2020-01-16 00:01 UTC, thebearingedge commented on client/components/app.jsx
> +// <Header/>,
Please remove commented out snips.

2020-01-16 00:07 UTC, AndrewRobins51413 commented
![Screen Shot 2020-01-15 at 4 05 51 PM](https://user-images.githubusercontent.com/55709702/72481972-fd337080-37b0-11ea-9957-841b7df64728.png)
![Screen Shot 2020-01-15 at 4 05 51 PM](https://user-images.githubusercontent.com/55709702/72482000-12100400-37b1-11ea-8c8d-2f782e9e462f.png)

2020-01-16 00:13 UTC, AndrewRobins51413 commented on client/components/app.jsx
> +// <Header/>,
I was not able to render multiple scripts through app.jsx. Not crucial for progress at the moment, but something I would like to know how to do.

2020-01-16 00:58 UTC, AndrewRobins51413 commented on package.json
> +    "react-bootstrap": "1.0.0-beta.16",
done

2020-01-16 01:01 UTC, AndrewRobins51413 commented on client/components/product-list.jsx
> +                </div> */}
My first effort did not involve bootstrap as much as I later realized it should have. I'll delete the non-bootstrap code when I have the bootstrap up and running.

2020-01-16 01:01 UTC, AndrewRobins51413 commented on client/components/product-list.jsx
> +// import ReactDOM from "react-dom"
done

2020-01-16 17:54 UTC, AndrewRobins51413 commented
![Screen Shot 2020-01-16 at 9 53 34 AM](https://user-images.githubusercontent.com/55709702/72549743-1e926c00-3846-11ea-9e84-930aaa03aae3.png)

2020-01-16 18:05 UTC, thebearingedge approved these changes

2020-01-16 18:06 UTC, merged